### ISSUE TITLE
Add ability to filter desired return results only

### ISSUE THREAD

**Issue by DenisBalan** [waxtell/Aop.Cache#17]
For example i dont want to cache specific return values like `null` or `0` or my record type `{ error: true, details: ... }`

It should be easy to add expectations as well for return values, not only for input arguments.

But overall, good library to make use of AOP in .NET.
Thanks.

**Comment by waxtell** [comment]
Hello and thank you for the kind words!

I like the idea of excluding specific return values.  I will try and carve out some time soon to implement the feature.

Thanks and Best Regards,
Will

**Comment by waxtell** [comment]
Hello @DenisBalan!  Please see version 3.2.0 as it supports result exclusion (per method only).

**Comment by DenisBalan** [comment]
@waxtell yeah, it works! :)
Thanks.

Also some other improvments could be some verbose logging (logging when entered permethodadapter, when generating cache key, input args, etc...), you could inject ILogger to use predefined settings from the app.

I'm using this AOP.Cache for 2nd level cache, so i have Redis with .net core `IDistributedCache`
And set up AOP.Cache for short-time living, so that when i have extensive processing, not going to redis directly, but just using `IMemoryCache`.
Very easy to enable and disable with your approach and Scrutor.

One question, i've testing with AddTransient, and that doesnt seem to work.
Why it's required to be AddSingleton for my class? or i'm missing smth..
```
                services.AddSingleton<IDistributedCacheAdoption, DistributedCacheAdoption>();

serviceCollection
                    .AddSingleton
                    (
                        provider =>
                        {
                            return
                                new PerMethodAdapter<IDistributedCacheAdoption>
                                    (
                                        CacheImplementationFactory
                                            .FromMemoryCache(provider.GetService<IMemoryCache>())
                                    )
                                    .Cache
                                    (
                                        x => x.GetFromCache(It.IsAny<string>(), It.IsAny<CancellationToken>()),
                                        Aop.Cache.ExpirationManagement.Expires.WhenInactiveFor(TimeSpan.FromMinutes(3)),
                                        result => (result.GetAwaiter().GetResult()) == null
                                    );
                        }
                    );

                serviceCollection
                    .Decorate<IDistributedCacheAdoption>
                    (
                        (inner, provider) => provider
                            .GetRequiredService<IPerMethodAdapter<IDistributedCacheAdoption>>()
                            .Adapt(inner)
                    );

```
Sample of the keys from `IMemoryCache` so it's easy to leverage logging (you have all the needed data already).
![image](https://user-images.githubusercontent.com/33955091/224319335-6b810bb3-14f5-4b13-9b07-02d11bc9bfac.png)

**Comment by waxtell** [comment]
The actual method adapter needs to be a singleton as it maintains a collection of expectations, etc.  Transient bindings for "adapted" instances is supported.  I updated the test console bindings to verify the aforesaid assertion.  Lastly, I just checked and many of the apps that I have written that leverage this library are also bound as transient.

Okay to close the exclusion issue then?

**Comment by DenisBalan** [comment]
Yes, feel free to close this one.
